language: python
python:
  - 3.7
addons:
  apt:
    sources:
      - sourceline: ppa:mosquitto-dev/mosquitto-ppa
    packages:
      - mosquitto
install:
  - python setup.py develop
  - pip install -e '.[dev]'
script:
  - isort .
  - black .
  - git diff --exit-code "*.py"
  - pylint src/paho_socket
  - pytest --cov=paho_socket
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: hCtakc9e+oEQYRG6mJwnxGOdFPvo+MRWsxhiDOTTh4i4Lbr/WWrRHlzf9ARBMk2dlSBdjJATvPifum668QdxGAEOikutQPMvO8dgzOEYnnSV0CxbygAn9ILgqbhQiCjuJ025ZL4TrsnWJR3k4rBtAw4IdWVVvoBEAoEOLngDOdNHYZpPC284NvwuRo9R3TDVr4hGrBVP+6jj1jw/U/QsuFQ6ffmRtuxs2uG2+BJXFhGGB7f1CpY0aC0QIeyilRy6SMjNKsoQh2rROolzaB7hYpH+t91uT7GGBIHMvMPRAmkmV7wQklcxoMyUb8NZLIWeNWaLmscTrwFKNwwI5bG4zi/3dXDWTG3aEqCsa11om3nzmJIq33o2nMZLI6uSE3OppPcFxhMFEL74PQJwe8f+W3K9qnWgTL1G8Yk6bLtRuLOV1JzXG9LfJzcOnerdKYygAfl7SSP3oBeEdDpU8M8f5Dq8jwT3e75OVqE6z2Ciie1wZF0IztxNZPYaGpSLgk8hE9bgWq1vwxptL++Lmj78KB/zDwft6P+J4tpKRgBotMnyXhP/3JaA8+vl9GW+ALngbirQAO++/TkqYTh21sAGmgflKwdNRwGq3PJVWk4KUmBQ+dEk7WfWiY7Y2Gm8XyTOtQBbouWB89bMpgL6KkJIg/bznne8WezKMgQu3ll1B+w=
  on:
    tags: true
